baseURL = "https://alanmond.com/"
languageCode = "en-us"
title = "Alan Mond's Blog"
theme = "PaperMod"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

# PaperMod-specific configurations can go here, too.
