alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: alanmond.com
  type: PRIMARY
  zone: alanmond.com
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: blog
    match:
      path:
        prefix: /
name: alan-blog
region: nyc
static_sites:
- dockerfile_path: ./Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: alan707/blog
  name: blog
  output_dir: /workspace/public
  source_dir: /